#!/usr/bin/env python3
"""
build_standalone.py
===================
Regenerate oic_sequence_gen_standalone.py from the package sources.

Run whenever the package sources change:

    python build_standalone.py

The script:
  1. Reads each source module in dependency order.
  2. Strips module-level docstrings and internal imports.
  3. Collects and deduplicates all stdlib imports.
  4. Writes a single self-contained Python file with section separators.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# ── Paths ─────────────────────────────────────────────────────────────────────

ROOT = Path(__file__).parent
SRC  = ROOT / "src" / "oic_sequence_gen"
OUT  = ROOT / "oic_sequence_gen_standalone.py"

# Modules in dependency order (no module may import one listed after it).
MODULES: list[tuple[str, Path]] = [
    ("constants",           SRC / "constants.py"),
    ("parser",              SRC / "parser.py"),
    ("generators/plantuml", SRC / "generators" / "plantuml.py"),
    ("generators/mermaid",  SRC / "generators" / "mermaid.py"),
    ("generators/png",      SRC / "generators" / "png.py"),
    ("cli",                 SRC / "cli.py"),
]

# ── File header ───────────────────────────────────────────────────────────────

FILE_HEADER = '''\
#!/usr/bin/env python3
"""
oic_sequence_gen_standalone.py
==============================
Single-file standalone version of oic-sequence-gen.

Generate PlantUML, Mermaid Markdown, and PNG sequence diagrams from
Oracle Integration Cloud (OIC) .iar export archives.

Requirements: Python 3.9+  —  no third-party packages needed.

Usage
-----
    python oic_sequence_gen_standalone.py --input integration.iar
    python oic_sequence_gen_standalone.py --input integration.iar --formats puml md png
    python oic_sequence_gen_standalone.py --input integration.iar --output ./docs --formats puml md

This file is auto-generated by build_standalone.py from the package sources.
For development, use the package directly via uv.
"""

from __future__ import annotations
'''

SECTION_SEP = "# {bar}\n# {label}\n# {bar}\n"


def _section(label: str) -> str:
    bar = "═" * 78
    return f"\n\n# {bar}\n# {label}\n# {bar}\n"


# ── Source processing ─────────────────────────────────────────────────────────

_INTERNAL_IMPORT = re.compile(
    r"^(?:from|import)\s+oic_sequence_gen"
)
_FUTURE_IMPORT = re.compile(
    r"^from\s+__future__\s+import\b"
)
_STDLIB_IMPORT = re.compile(
    r"^(?:import\s+\w|from\s+\w)"
)


def _strip_module_docstring(lines: list[str]) -> list[str]:
    """
    Remove the leading module docstring (if any) from a list of source lines.
    Handles both triple-double-quote and triple-single-quote docstrings.
    """
    i = 0
    # Skip blank lines before the docstring
    while i < len(lines) and lines[i].strip() == "":
        i += 1

    if i >= len(lines):
        return lines

    first = lines[i].strip()
    if not (first.startswith('"""') or first.startswith("'''")):
        return lines  # no docstring

    quote = first[:3]
    # Check if it opens and closes on the same line (and has content after)
    rest = first[3:]
    if rest.endswith(quote) and len(rest) >= len(quote):
        return lines[i + 1:]  # single-line docstring

    # Multi-line: scan forward for the closing triple-quote
    i += 1
    while i < len(lines):
        if quote in lines[i]:
            return lines[i + 1:]
        i += 1

    return lines  # malformed — return as-is


def _process_module(path: Path) -> tuple[list[str], list[str]]:
    """
    Return (stdlib_imports, body_lines) for a single source module.

    - Module docstring is stripped.
    - `from __future__ import` lines are stripped (emitted once at top).
    - `from oic_sequence_gen.*` / `import oic_sequence_gen.*` lines stripped.
    - All other `import` / `from` lines are collected as stdlib_imports.
    - The remainder becomes body_lines.
    """
    raw = path.read_text(encoding="utf-8").splitlines(keepends=True)
    lines = _strip_module_docstring(raw)

    stdlib_imports: list[str] = []
    body_lines:     list[str] = []

    for line in lines:
        stripped = line.strip()
        if not stripped:
            body_lines.append(line)
            continue
        if _FUTURE_IMPORT.match(stripped):
            continue
        if _INTERNAL_IMPORT.match(stripped):
            continue
        if _STDLIB_IMPORT.match(stripped):
            stdlib_imports.append(line.rstrip("\n"))
            continue
        body_lines.append(line)

    return stdlib_imports, body_lines


# ── Version extraction ────────────────────────────────────────────────────────

def _extract_version() -> str:
    init = SRC / "__init__.py"
    for line in init.read_text(encoding="utf-8").splitlines():
        m = re.match(r'^__version__\s*=\s*["\'](.+)["\']', line)
        if m:
            return m.group(1)
    return "0.0.0"


# ── Main ──────────────────────────────────────────────────────────────────────

def build() -> None:
    all_stdlib:  list[str] = []
    all_sections: list[tuple[str, list[str]]] = []

    for label, path in MODULES:
        if not path.exists():
            print(f"ERROR: source file not found: {path}", file=sys.stderr)
            sys.exit(1)
        stdlib_imports, body = _process_module(path)
        all_stdlib.extend(stdlib_imports)
        all_sections.append((label, body))

    # Deduplicate stdlib imports while preserving first-seen order
    seen: set[str] = set()
    unique_stdlib: list[str] = []
    for imp in all_stdlib:
        key = imp.strip()
        if key not in seen:
            seen.add(key)
            unique_stdlib.append(imp)

    # ── Assemble output ───────────────────────────────────────────────────────
    parts: list[str] = [FILE_HEADER]

    # stdlib imports block
    parts.append("\n")
    parts.append("# ── stdlib imports ───────────────────────────────────────────────────────────\n")
    parts.extend(line + "\n" for line in unique_stdlib)

    # __version__
    version = _extract_version()
    parts.append(f'\n__version__ = "{version}"\n')

    # Module sections
    for label, body_lines in all_sections:
        section_title = label.upper().replace("/", " — ")
        parts.append(_section(section_title))
        parts.extend(body_lines)

    # Entry point guard (cli section already contains main(); add the guard)
    parts.append('\n\nif __name__ == "__main__":\n    main()\n')

    output = "".join(parts)

    OUT.write_text(output, encoding="utf-8")
    print(f"Written: {OUT.relative_to(ROOT)}  ({len(output):,} bytes, {output.count(chr(10))} lines)")


if __name__ == "__main__":
    build()
